[workspace]
members = [
    "chains/evm",
    "cli",
    "bridge",
    "guests",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
homepage = "https://0xhacked.com/"
repository = "https://github.com/0xHackedLabs/zkProver"

[profile.release]
# Optimize for binary size, but keep loop vectorization
opt-level = "s"
# Performance optimizations
lto = "fat"
debug = 0
strip = true
panic = "abort"
codegen-units = 1